### PR TITLE
rpc: Implement GetOrders RPC method

### LINKED ISSUE #86: rpc: Add paginated get all orders in DB method
We have designed Mesh such that if it crashes for any reason, it resumes from where it left off upon re-start. This means clients will receive all order events despite the disruption. But what if the client is disrupted? The order event subscriptions won't queue up until their return.

In order to handle this scenario, we will add a paginated method for fetching all orders currently in the Mesh database. This will allow a client that has crashed to update all the orders in their DB/in-memory store and recover to an up-to-date snapshot of the valid orders stored by the Mesh node.

### PR DESCRIPTION
**Pull request by fabioberger**
Fixes #86

### CODE REVIEW

File: core/core.go [hunk 1]
```diff
@@ -233,6 +265,86 @@ func (app *App) periodicallyCheckForNewAddrs(startingAddrs []ma.Multiaddr) {
...
+	id string
+}
+
+func (e ErrSnapshotNotFound) Error() string {
+	return fmt.Sprintf("No snapshot found with id: %s. To create a new snapshot, send a request with an empty snapshotID", e.id)
+}
+
+// GetOrders retrieves paginated orders from the Mesh DB at a specific snapshot in time. Passing an empty
+// string as `snapshotID` creates a new snapshot and returns the first set of results. To fetch all orders,
+// continue to make requests supplying the `snapshotID` returned from the first request.
```
Comment (albrow) [inline core/core.go]: Maybe we should add to this doc comment the fact the snapshots expire after 1 minute of receiving no requests for that snapshot?

File: core/core.go [hunk 2]
```diff
@@ -6,18 +6,23 @@ package core
 import (
 	"context"
 	"fmt"
+	"sync"
 	"time"
 
+	dbPkg "github.com/0xProject/0x-mesh/db"
```
[the remark this answers is not in the document]
Comment (fabioberger) [reply core/core.go]: There was a collision with a variable names `db`, but on second thought, I decided to rename the variable and leave the package name as `db`.

File: core/core.go [hunk 3]
```diff
@@ -233,6 +265,87 @@ func (app *App) periodicallyCheckForNewAddrs(startingAddrs []ma.Multiaddr) {
...
+}
+
+func (e ErrSnapshotNotFound) Error() string {
+	return fmt.Sprintf("No snapshot found with id: %s. To create a new snapshot, send a request with an empty snapshotID", e.id)
+}
+
+// GetOrders retrieves paginated orders from the Mesh DB at a specific snapshot in time. Passing an empty
+// string as `snapshotID` creates a new snapshot and returns the first set of results. To fetch all orders,
+// continue to make requests supplying the `snapshotID` returned from the first request. After 1 minute of not
+// received further requests referencing a specific snapshot, the snapshot expires and can no longer be used.
```
Comment (albrow) [inline core/core.go]:
```suggestion
// receiving further requests referencing a specific snapshot, the snapshot expires and can no longer be used.
```
