### PR TITLE
Final changes to make all code follow our async conventions

### LINKED ISSUE #96: Make asynchronous APIs more consistent
When we first started building 0x Mesh, we weren't certain about the best practices for writing asynchronous APIs in Go and had to consider a wide variety of unexpected use cases and constraints. At this point, enough of the pieces are in place that we should be able to go back and choose a general set of guidelines to apply to all of our asynchronous code. 

Here are some general rules I'm proposing:

1. Avoid exporting non-blocking functions/methods. Instead, mimic methods from the standard library like [`http.ListenAndServe`](https://golang.org/pkg/net/http/#ListenAndServe), which blocks until there is an error. Callers can wrap this in a goroutine if needed.
2. Don't expose channels in exported functions, methods, or fields.
3. Whenever we do continuous computation in a for loop (i.e. a for loop without a post statement) we should check for [`context.Done`](https://golang.org/pkg/context/#Context). This usually necessitates accepting a `context.Context` as an argument.
4. Don't use `context.Background` except in tests and __main.go__.
5. Don't use a `Close` method. Just cancel the context.
6. Don't pass in timeouts as a `time.Duration`. Just use a context and expect the caller to use `context.WithTimeout` if they need timeouts.

There are of course going to be some exceptions (e.g. `go-ethereum/rpc` requires us to have an exported method which returns a channel), but I think using a set of guidelines will make it a lot easier for us to maintain the code going forward.

### PR DESCRIPTION
**Pull request by albrow**
Fixes #96.

Depends on #307. After that PR is merged I'll change the base branch for this one to `development`.

Summary of changes:
- Make `core.App.Start` blocking.
- Remove `core.App.Stop`.
- Avoid `log.Panic` and `log.Fatal` whenever possible (there are some lingering cases where e.g., we pass a function into another function and don't have a good way to return errors).
- Remove the `blockwatch.Watcher.Errors` channel. For non-critical errors, we log them in `blockwatch.Watcher` directly. For critical errors, we return them in `blockwatch.Watcher.Watch`. This makes `blockwatch` more aligned with the rest of our async code.
- Don't start any goroutines without a way to stop them (usually by waiting for `ctx.Done()` but sometimes with short timeouts or other signals).

### CODE REVIEW

File: ethereum/blockwatch/block_watcher.go [hunk 1]
```diff
@@ -426,6 +420,12 @@ func (w *Watcher) getLogsInBlockRange(from, to int) ([]types.Log, int) {
 			go func(index int, b *blockRange) {
 				defer wg.Done()
 
+				select {
+				case <-ctx.Done():
+					return
```
Comment (fabioberger) [inline ethereum/blockwatch/block_watcher.go]: We need to add an entry to `indexToLogResult` before returning otherwise the code below will panic. It expects there to be an entry for every index.

Let's set it to:
```
indexToLogResult[index] = logRequestResult{
					From: b.FromBlock,
					To:   b.ToBlock,
					Err:  errors.New("Parent context was canceled"),
					Logs: []types.Log{},
				}
```

Comment (albrow) [reply ethereum/blockwatch/block_watcher.go]: Just added this.
